Testing
wetransform-os/portrayal-repository pull request #19
Opened 2020-10-26 09:59 UTC by Kate-Lyndegaard

In this PR, I reviewed/fixed all layer titles and rule titles.

2020-10-28 09:20 UTC, JohannaOtt requested changes
I found some things, where the different titles are not aligned but I don't know if that is maybe a result of different rules in the DS.
I did not do a detailed review as that would include publishing datasets for all themes and I guess we can still react here in case issues occur in the future. What do you think  @Kate-Lyndegaard ?

2020-10-28 09:20 UTC, JohannaOtt commented on feature-styles/HH_HealthDeterminantMeasure.se
> +      <se:Title>Human health polygon</se:Title>
For Renewable and Waste Resource, polygonS and lineS are used in plural - here they are used in singular - maybe align?

2020-10-28 09:20 UTC, JohannaOtt commented on feature-styles/PS_ProtectedSites.se
> +      <se:Title>Protected sites: polygon</se:Title>
For other FeatureTypes with different geometries the colon between Type and geometry has been removed - maybe align.

2020-10-28 09:20 UTC, JohannaOtt commented on feature-styles/HY_P_WaterbodiesPersistence.se
> +      <se:Title>Standing waters persistence: perennial</se:Title>
For other cases with different geometries, the geometry was mentioned in the title - maybe align?

2020-10-28 09:20 UTC, JohannaOtt commented on feature-styles/HY_P_WatercoursePersistence.se
> +      <se:Title>Waterbodies persistence: perennial</se:Title>
For other cases with different geometries, the geometry was mentioned in the title - maybe align?

2020-10-28 09:20 UTC, JohannaOtt commented on feature-styles/HY_P_WatercoursePersistence.se
> +      <se:Title>Waterbodies persistence: intermittent</se:Title>
For other cases with different geometries, the geometry was mentioned in the title - maybe align?

2020-10-28 09:20 UTC, JohannaOtt commented on feature-styles/HY_P_WatercoursePersistence.se
> +      <se:Title>Waterbodies persistence: ephemeral or dry</se:Title>
For other cases with different geometries, the geometry was mentioned in the title - maybe align?

2020-10-28 09:20 UTC, JohannaOtt commented on feature-styles/HY_P_Watercourse_ManMade.se
> +      <se:Title>Waterbodies natural</se:Title>
For other cases with different geometries, the geometry was mentioned in the title - maybe align?

2020-10-28 09:20 UTC, JohannaOtt commented on feature-styles/HY_P_Watercourse_ManMade.se
> +      <se:Title>Waterbodies man-made</se:Title>
For other cases with different geometries, the geometry was mentioned in the title - maybe align?

2020-10-28 11:17 UTC, Kate-Lyndegaard commented
> 
> 
> I found some things, where the different titles are not aligned but I don't know if that is maybe a result of different rules in the DS.
> I did not do a detailed review as that would include publishing datasets for all themes and I guess we can still react here in case issues occur in the future. What do you think @Kate-Lyndegaard ?

I think this is great and I knew you would comment on this:-O
I am also unsure how to handle this. In the original template files, some INSPIRE SLDs referenced the geometry type in the rule title. This means that it will appear in the legend as follows:

<square icon> protected sites: polygon
<line icon> protected sites: line.... etc

The textual description of the geometry seems redundant because you already have the icon clearly indicating the geometry type!
If you remove the geometry type, however, then you have three identical labels: 

<square icon> protected sites
<line icon> protected sites

2020-10-29 08:14 UTC, JohannaOtt commented
I personally would prefer to add the geometries to the legend - I think identical labels look a bit weird. So even if it is obvious with the symbols, I would add the geometry type.

2020-10-29 14:47 UTC, JohannaOtt approved these changes

2020-10-30 09:42 UTC, merged